### PR TITLE
Use OAuth Resource Server starter #73

### LINKED ISSUE #73: Update example to use Keycloak via Spring Security instead of starter for Spring Boot 2.3

### PR DESCRIPTION
**Pull request by gytis**
I left the Keycloak client in the tests because that is a complex setup and requires a separate investigation of how to better reimplement it. 
I also left the Javascript as is but I think we should look into replacing it with another Java module.

Same as before, I had to disable Trust Manager because our test and local Keycloak installations do not have proper SSL sertificates.

### CODE REVIEW

**Comment by gytis** [comment]
OpenShift test failed because the app failed to get configuration from the Keycloak. Rerunning with SSH to see what's happening.

**Comment by gytis** [comment]
If I run the application inside CircleCI it fails to access `https://secure-sso-fmp.127.0.0.1.nip.io/auth/realms/master` and gets `503 Service not available`. However, if I curl the same address I get a valid response.

**Comment by gytis** [comment]
If I deploy a Keycloak server on Hetzner and try to run identical Spring Boot applications locally and on CircleCI, the local one works but the CircleCI fails in the same way as before.

**Comment by gytis** [comment]
Added `jwk-set-uri` property, hopefully that will solve the problem.

**Comment by gytis** [comment]
For some reason the test passes if a Keycloak is running on Hetzner but not if it's running on CircleCI.

**Comment by gytis** [comment]
On CircleCI `NimbusJwtDecoder` token validation fails. It tries verifying the certificate with Keycloak at `${SSO_AUTH_SERVER_URL}/realms/master/protocol/openid-connect/certs` and get's 503 error. Both locally ran application and `curl` from CircleCI can access that same path without issues.

**Review by aureamunoz — APPROVED** [review]
LGTM

**Comment by gytis** [comment]
So finally I managed to find a working setup. I've configured Spring Security to verify a JWT with a locally stored public key instead of delegating this task to a Keycloak server. This is a valid solution but does need an extra configuration (default is to contact the server). I don't think there is another option with the current CircleCI OpenShift setup.
If we would have an OpenShift server with a publicly available IP address and a Keycloak server with valid SSL certificates the example could be much cleaner and smaller.

@aureamunoz @metacosm could you review this again?

**Review by aureamunoz — APPROVED** [review]
LGTM.

**Pull request merged**
