### PR TITLE
Unification of error messages across runtimes for e2e test

### PR DESCRIPTION
**Pull request by akoniar**

### CODE REVIEW

**Comment by geoand** [comment]
test this please

**Comment by geoand** [comment]
Our internal tests are failing at the moment (I am almost certain that this PR is not to blame), but we should probably hold off on accepting until we can verify the root cause of the failure

**Comment by geoand** [comment]
@Ladicek Thank you for the update. 

I guess we should wait for the aforementioned PRs then, and afterwards take a look at this one

**Comment by metacosm** [comment]
test this please

**Comment by Ladicek** [comment]
Yay, it works! :-)

**Comment by metacosm** [comment]
Thank you, @akoniar!

**Pull request merged**
