### PR TITLE
[SB-305] replace sso.auth.server.url with SSO_AUTH_SERVER_URL

### PR DESCRIPTION
**Pull request by gytis**
https://issues.jboss.org/browse/SB-305

### CODE REVIEW

**Comment by metacosm** [comment]
Otherwise, looks good to me. 👍

**Comment by gytis** [comment]
@metacosm good point, thanks!

**Comment by cmoulliard** [comment]
Good to me too. We can merge it

**Comment by gytis** [comment]
@metacosm updated. I've added it to the openshift profile only. Not sure if it will be needed by the tests once they're updated to use Cube. They don't work for me at all now.
Alternatively, we could add it to the build section and enforce even for the local runs (which it is needed anyway)

**Comment by metacosm** [comment]
Thanks!

**Pull request merged**
